/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: [
    'antd',
    '@ant-design/icons',
    '@ant-design/icons-svg',
    'rc-util',
    'rc-pagination',
    'rc-picker',
    'rc-notification',
    'rc-tooltip',
    'rc-tree',
    'rc-table',
    'rc-dropdown',
    'rc-menu',
    'rc-input',
    'rc-textarea',
    'rc-select',
    'rc-checkbox',
    'rc-radio',
    'rc-upload',
    'rc-progress',
    'rc-motion',
    'rc-field-form',
    'rc-resize-observer',
    '@rc-component/trigger',
    '@rc-component/util',
    '@rc-component/context',
    '@rc-component/portal',
    '@rc-component/pagination',
    '@rc-component/color-picker',
    '@rc-component/table',
    '@rc-component/tree',
    '@rc-component/mini-decimal',
  ],
}

module.exports = nextConfig
